# SPDX-FileCopyrightText: 2021 Philipp Basler, Margarete Mühlleitner and Jonas Müller
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Ubuntu unit tests

on:
  push:
    branches: [ main, feature/addTWrap ]
  pull_request:
    branches: [ main, feature/addTWrap ]
  workflow_dispatch:
    

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
          persist-credentials: false
    - name : installPackages
      run : sudo apt-get update && sudo apt-get install --no-install-recommends --yes libeigen3-dev libbenchmark-dev libgtest-dev
    - name: Get number of CPU cores
      uses: SimenB/github-actions-cpu-cores@v1
      id: cpu-cores
    - name: cmake
      run: mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release
    - name: compile
      run: cd build && cmake --build . -j${{ steps.cpu-cores.outputs.count }} --config Release
    - name: Test
      run: cd build && ctest -j${{ steps.cpu-cores.outputs.count }} --output-on-failure
      



