# SPDX-FileCopyrightText: 2021 Philipp Basler, Margarete Mühlleitner and Jonas Müller
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Ubuntu unit tests

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main, develop ]
  workflow_dispatch:
    

jobs:
  ubuntu-tests:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-ci')"

    steps:
    - uses: actions/checkout@v3
      with:
          persist-credentials: false
    - name: Get number of CPU cores
      uses: SimenB/github-actions-cpu-cores@v1
      id: cpu-cores
    - name: cmake
      run: mkdir build && cd build && cmake .. 
    - name: make
      run: cd build && cmake --build . -j${{ steps.cpu-cores.outputs.count }}
    - name: Test
      run: cd build && ctest -j${{ steps.cpu-cores.outputs.count }} --output-on-failure
      


